### PR TITLE
Internationalize and localize vnote documentation using Sphinx i18n feature

### PR DESCRIPTION
**Pull request by miurahr**
Sphinx has an i18n feature to use gettext PO message catalog.
This helps us to produce multi language site from single source documents.

Here is a PR that does

- Configure and activate Sphinx I18N feature
- Add Chinese translations as a PO file which messages from vnote-docs-zh_CN repository.
- Add Japanese translations as a PO file.

To generate localized document;
```
$ make html
```

This produce English, Chinese and Japanese HTML files in _build/html/(lang) folder.

Also you can use [Crowdin](https://crowdin.com/), [Transifex,](https://www.transifex.com/) or [TranslateWiki](https://translatewiki.net/), for translation project hosting service.

## How to add new language 

You can  easily add new language. 

1. Genate POT files.

```
$ make gettext
```
The generated pot files will be placed in the _build/gettext directory.

2. Generate po files for  languages
We’ll use the pot files in _build/gettext generated in the above step.
If message catalog for specified language is not exist, it is automatically created.
otherwise update po files.

```
$ sphinx-intl update -p _build/gettext -l de -l zh_CN
```

3. Update all po files by new pot files

If a document is updated, it is necessary to generate updated pot files and to apply differences to translated po files. In order to apply the updates from a pot file to the po file, use the sphinx-intl update command.

```
$ sphinx-intl update -p _build/gettext
```

cf. http://www.sphinx-doc.org/en/master/usage/advanced/intl.html

### CODE REVIEW

**Comment by tamlok** [comment]
Wow! Great work!

Since ReadTheDocs uses a different Markdown renderer as VNote does, I have migrated the documentation from it to Viki [here](https://tamlok.github.io/vnote/en_us/#!docs/Users/welcome.md).

With Viki, the documentation of VNote is now a notebook of VNote and they use exactly the same renderer. However we need to maintain separate translations and Viki does not support full text search.

For now VNote's documentation only provides two languages. I think it is OK to maintian other translations using ReadTheDocs if i18n feature is feasible.

Thank you very much!

**Comment by miurahr** [comment]
Using this approach, we can use systematic approach for translations.
Wiki style looks easy but difficult manage consistent result.

When English version is updated, how to track chages translated document?

In wiki it is impossible without human check, but the approch automatically detect it.
Translation tool like OmegaT treat it smat way.

**Comment by tamlok** [comment]
Yeah, ReadTheDocs is still a better place to hold documentation.

BTW, do we need extra changes to make it take effect to show the translations? I do not see any translations option [here](https://vnote.readthedocs.io/en/latest/).

**Comment by miurahr** [comment]
See procedure at https://docs.readthedocs.io/en/latest/localization.html
You must commit the .po files for Read the Docs to translate your documentation.

https://docs.readthedocs.io/en/latest/guides/manage-translations.html
I've already place files as document described.

**Comment by tamlok** [comment]
Still can not figure out how to make the translation available. Do you mind to be a contributor of [vnote's docs](https://readthedocs.org/dashboard/vnote/users/)? If so, tell me your account name and I will add it to the dashboard, so you could help to make the translations available. :) Thanks!

**Comment by miurahr** [comment]
My Account is `miurahr`, you may be able to see translation configuration at https://readthedocs.org/dashboard/vnote-docs/translations/  and add language to show.

**Comment by tamlok** [comment]
Added as maintainer. Could you take a look?

**Comment by miurahr** [comment]
I worked to enable. here is a procedure.

1. Create each language document project on readthedocs.org using same git URL here but set `language` property  properly.

2. Goto `Admin` menu, select `translation` menu, select project created in step 1.

3. You can see language switch menu in main document.

capture1
capture3
capture4
capture5
capture6
capture7
capture8

**Comment by miurahr** [comment]
I'd worked for chinese too.
Now you can manage two languages here.

**Comment by tamlok** [comment]
> I'd worked for chinese too.
> Now you can manage two languages here.

Thank you very much!

**Pull request merged**
